"""
AI-Assisted Risk-Adaptive MFA
--------------------------------
Graph generator for the synthetic authentication experiment.

Reads:
    synthetic_authentication_dataset.csv
    model_comparison.csv
    feature_importance.csv

Creates:
    1. risk_distribution.png
    2. model_performance.png
    3. confusion_matrix.png
    4. feature_importance.png
    5. security_usability.png

All graphs are generated using Matplotlib.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# ============================================================
# 1. LOAD DATA
# ============================================================

dataset = pd.read_csv(
    "synthetic_authentication_dataset.csv"
)

model_results = pd.read_csv(
    "model_comparison.csv"
)

feature_results = pd.read_csv(
    "feature_importance.csv"
)


# ============================================================
# 2. GLOBAL GRAPH SETTINGS
# ============================================================

plt.rcParams.update({
    "figure.dpi": 150,
    "savefig.dpi": 300,
    "font.size": 11,
    "axes.titlesize": 15,
    "axes.labelsize": 12,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10
})


# ============================================================
# GRAPH 1 — RISK DISTRIBUTION
# ============================================================

risk_counts = (
    dataset["risk_level"]
    .value_counts()
    .reindex(["Low", "Medium", "High"])
)

fig, ax = plt.subplots(figsize=(8, 5))

bars = ax.bar(
    risk_counts.index,
    risk_counts.values
)

ax.set_title(
    "Distribution of Simulated Authentication Risk Levels"
)

ax.set_xlabel(
    "Risk Level"
)

ax.set_ylabel(
    "Number of Authentication Events"
)

ax.grid(
    axis="y",
    alpha=0.25
)

for bar, value in zip(bars, risk_counts.values):

    ax.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 100,
        str(value),
        ha="center",
        va="bottom"
    )

plt.tight_layout()

plt.savefig(
    "risk_distribution.png",
    bbox_inches="tight"
)

plt.show()


# ============================================================
# GRAPH 2 — MODEL PERFORMANCE
# ============================================================

metrics = [
    "Accuracy",
    "Precision",
    "Recall",
    "F1"
]

x = np.arange(len(metrics))

width = 0.35

rule_based = (
    model_results
    .loc[
        model_results["Model"] == "Rule-based",
        metrics
    ]
    .values[0]
)

ai_model = (
    model_results
    .loc[
        model_results["Model"] == "AI Decision Tree",
        metrics
    ]
    .values[0]
)

fig, ax = plt.subplots(figsize=(9, 5))

bars1 = ax.bar(
    x - width / 2,
    rule_based,
    width,
    label="Rule-based"
)

bars2 = ax.bar(
    x + width / 2,
    ai_model,
    width,
    label="AI Decision Tree"
)

ax.set_title(
    "Comparison of Risk Classification Performance"
)

ax.set_ylabel(
    "Score"
)

ax.set_xticks(x)

ax.set_xticklabels(metrics)

ax.set_ylim(0, 1)

ax.grid(
    axis="y",
    alpha=0.25
)

ax.legend()

for bars in [bars1, bars2]:

    for bar in bars:

        ax.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 0.02,
            f"{bar.get_height():.2f}",
            ha="center",
            va="bottom",
            fontsize=9
        )

plt.tight_layout()

plt.savefig(
    "model_performance.png",
    bbox_inches="tight"
)

plt.show()


# ============================================================
# GRAPH 3 — CONFUSION MATRIX
# ============================================================

# Reconstruct the confusion matrix from the results
# generated by the experiment.

# The values come directly from your current experiment.
# Later, we will make the calculations program save this
# automatically so this graph does not depend on manual values.

confusion = np.array([
    [1324, 32, 0],
    [172, 339, 14],
    [12, 30, 77]
])

labels = [
    "Low",
    "Medium",
    "High"
]

fig, ax = plt.subplots(figsize=(7, 6))

image = ax.imshow(
    confusion
)

ax.set_title(
    "AI Risk Classification Confusion Matrix"
)

ax.set_xlabel(
    "Predicted Risk Level"
)

ax.set_ylabel(
    "Actual Risk Level"
)

ax.set_xticks(
    np.arange(len(labels))
)

ax.set_yticks(
    np.arange(len(labels))
)

ax.set_xticklabels(labels)

ax.set_yticklabels(labels)

for i in range(len(labels)):

    for j in range(len(labels)):

        ax.text(
            j,
            i,
            confusion[i, j],
            ha="center",
            va="center"
        )

plt.colorbar(
    image,
    ax=ax,
    label="Number of Events"
)

plt.tight_layout()

plt.savefig(
    "confusion_matrix.png",
    bbox_inches="tight"
)

plt.show()


# ============================================================
# GRAPH 4 — FEATURE IMPORTANCE
# ============================================================

feature_plot = (
    feature_results
    .sort_values(
        "importance",
        ascending=True
    )
)

fig, ax = plt.subplots(figsize=(9, 6))

bars = ax.barh(
    feature_plot["feature"],
    feature_plot["importance"]
)

ax.set_title(
    "Feature Importance in AI Risk Classification"
)

ax.set_xlabel(
    "Relative Importance"
)

ax.set_ylabel(
    "Authentication Context Feature"
)

ax.grid(
    axis="x",
    alpha=0.25
)

for bar, value in zip(
    bars,
    feature_plot["importance"]
):

    ax.text(
        value + 0.005,
        bar.get_y() + bar.get_height() / 2,
        f"{value:.3f}",
        va="center"
    )

plt.tight_layout()

plt.savefig(
    "feature_importance.png",
    bbox_inches="tight"
)

plt.show()


# ============================================================
# GRAPH 5 — SECURITY VS USABILITY
# ============================================================

high_risk_recall = 0.6471

friction_rate = 0.0074

security_value = high_risk_recall * 100

friction_value = friction_rate * 100

categories = [
    "High-risk detection\n(recall)",
    "Unnecessary escalation\n(friction)"
]

values = [
    security_value,
    friction_value
]

fig, ax = plt.subplots(figsize=(8, 5))

bars = ax.bar(
    categories,
    values
)

ax.set_title(
    "Security Detection and Authentication Friction"
)

ax.set_ylabel(
    "Percentage (%)"
)

ax.grid(
    axis="y",
    alpha=0.25
)

for bar, value in zip(bars, values):

    ax.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 1,
        f"{value:.2f}%",
        ha="center",
        va="bottom"
    )

plt.tight_layout()

plt.savefig(
    "security_usability.png",
    bbox_inches="tight"
)

plt.show()


# ============================================================
# FINAL MESSAGE
# ============================================================

print("\n==============================")
print("GRAPH GENERATION COMPLETE")
print("==============================")

print("Created:")

print("1. risk_distribution.png")
print("2. model_performance.png")
print("3. confusion_matrix.png")
print("4. feature_importance.png")
print("5. security_usability.png")